#!/bin/bash
sudo apt update -qq
sudo apt install -y -qq wget

cd ..
mkdir -p server
cd server

sudo wget "https://git.magmafoundation.org/api/v4/projects/103/packages/maven/org/magmafoundation/Magma/1.19.3-44.1.23-ef6188f2/Magma-1.19.3-44.1.23-ef6188f2-server.jar" -o server.jar
